# App Identification
spring.application.name=allotment-service
server.port=8082

# Isolated Database Connection Parameters
# (Make sure hms_allotment_db matches your local PostgreSQL setup, or point it to your target database)
spring.datasource.url=jdbc:postgresql://localhost:5432/hms_allotment_db
spring.datasource.username=postgres
spring.datasource.password=your_password_here
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Link back to Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/