# ===================================================================
# App Identification & Network Routing
# ===================================================================
spring.application.name=patient-service
server.port=8081

# ===================================================================
# Live Render Cloud Database Connection (MediLinkDB)
# ===================================================================
# Swap out 'dpg-xxxxx-a' and 'dummy_db_name' with your actual Render credentials
spring.datasource.url=jdbc:postgresql://dpg-d8a1qqq8qa3s73ef4leg-a.oregon-postgres.render.com:5432/medilinkdb?ssl=true&sslmode=require
# Tell Hibernate to automatically create missing tables on startup
spring.jpa.hibernate.ddl-auto=update
# localhost:5432/Hospital_Management_DB

spring.datasource.username=medilinkdb_user
#postgres

spring.datasource.password=6JoVFMV933hfXh0tcMkZebIfi8HbvzZ4
#postgresql23

spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# Hikari Connection Pooling Optimization for Cloud Latency
# ===================================================================
# Prevents cloud connection dropouts and idle timeouts
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# ===================================================================
# Discovery Service Layer Registry Link
# ===================================================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Disable Eureka registration for cloud standalone execution
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false