spring.application.name=my-springboot-project

spring.datasource.url=jdbc:postgresql://dpg-d8a1qqq8qa3s73ef4leg-a:5432/medilinkdb
spring.datasource.username=medilinkdb_user
spring.datasource.password=6JoVFMV933hfXh0tcMkZebIfi8HbvzZ4

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true