spring.application.name=my-springboot-project
spring.datasource.url=jdbc:postgresql://localhost:5432/Hospital_Management_DB
spring.datasource.username=postgres
spring.datasource.password=postgresql23

spring.datasource.driver-class-name=org.postgresql.Driver